/*
   2. UNIQUE 제약조건
      컬럼에 입력 값이 중복된 값을 가질 수 없도록 제한하는 제약조건이다.
*/


-- 아이디가 중복되어도 성공적으로 데이터가 삽입된다.
INSERT INTO MEMBER VALUES('USER1', '1234', '김삿갓', DEFAULT);
INSERT INTO MEMBER VALUES('USER1', '1234', '이몽룡', DEFAULT);


-- (1) 테이블 생성 (UNIQUE 제약조건)
-- 테이블 삭제
DROP TABLE MEMBER;

-- 테이블 생성
CREATE TABLE MEMBER (
   ID VARCHAR2(20) NOT NULL UNIQUE,
   PASSWORD VARCHAR2(20) NOT NULL,
   NAME VARCHAR2(15) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE
);

-- 정상적으로 INSERT 됨
INSERT INTO MEMBER VALUES('USER1', '1234', '김삿갓', DEFAULT);
-- UNIQUE 제약조건에 위배되어 INSERT 실패
INSERT INTO MEMBER VALUES('USER1', '1234', '이몽룡', DEFAULT);

-- 어떤 것이 위배되었는지 확인 할 수 있으나, 직관적이지 않음
SELECT UC.CONSTRAINT_NAME, 
       UC.TABLE_NAME, 
       UCC.COLUMN_NAME, 
       UC.CONSTRAINT_TYPE
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'MEMBER';


-- (2) 테이블 생성 (UNIQUE 제약조건)
-- UNIQUE 조건을 테이블 레벨로 지정하는 방식
-- 제약조건에 이름을 주어, 제약조건이 걸렸을 시 알아보기 쉽게 할 수 있다.

-- 테이블 삭제
DROP TABLE MEMBER;

-- 테이블 생성
CREATE TABLE MEMBER (
   NO NUMBER CONSTRAINT MEMBER_NO_NN NOT NULL,
   ID VARCHAR2(20) CONSTRAINT MEMBER_ID_NN NOT NULL,
   PASSWORD VARCHAR2(20) CONSTRAINT MEMBER_PASSWORD_NN NOT NULL,
   NAME VARCHAR2(15) CONSTRAINT MEMBER_NAME_NN NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT MEMBER_ID_UQ UNIQUE(ID) -- 테이블 레벨로 지정
);

-- 정상적으로 INSERT 됨
INSERT INTO MEMBER VALUES('USER1', '1234', '김삿갓', DEFAULT);
-- 위배된 제약조건에 네이밍된 것이 출력
INSERT INTO MEMBER VALUES('USER1', '1234', '이몽룡', DEFAULT);

-- 어떤 것이 위배되었는지 확인 할 때 네이밍된 것이 출력
SELECT UC.CONSTRAINT_NAME, 
       UC.TABLE_NAME, 
       UCC.COLUMN_NAME, 
       UC.CONSTRAINT_TYPE
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'MEMBER';


-- (3) 테이블 생성 (UNIQUE 제약조건)
-- 여러 개의 컬럼을 묶어서 하나의 UNIQUE 제약조건으로 설정할 수 있다. 
-- (단, 반드시 테이블 레벨로만 설정이 가능하다.)

-- 테이블 삭제
DROP TABLE MEMBER;

-- 테이블 생성 
CREATE TABLE MEMBER (
   NO NUMBER NOT NULL,
   ID VARCHAR2(20) NOT NULL,
   PASSWORD VARCHAR2(20) NOT NULL,
   NAME VARCHAR2(15) NOT NULL,
   ENROLL_DATE DATE DEFAULT SYSDATE,
   CONSTRAINT MEMBER_NO_ID_UQ UNIQUE(NO, ID) -- 테이블 레벨로 지정
);

-- 정상적으로 INSERT 됨
INSERT INTO MEMBER VALUES(1, 'USER1', '1234', '김삿갓', DEFAULT);
-- NO가 같고 ID가 같은 경우 : 오류
INSERT INTO MEMBER VALUES(1, 'USER1', '1234', '이몽룡', DEFAULT);
-- NO가 같고 ID가 다른 경우 : 오류
INSERT INTO MEMBER VALUES(1, 'USER1', '1234', '이몽룡', DEFAULT);
-- NO가 다르고 ID가 같은 경우 : 정상적으로 INSERT 됨
INSERT INTO MEMBER VALUES(2, 'USER1', '1234', '이몽룡', DEFAULT);

-- 묶여있는 컬럼들의 제약조건이 같게 나옴
-- 두개 컬럼의 값이 완전히 동일해야 제약조건에 걸림
SELECT UC.CONSTRAINT_NAME, 
       UC.TABLE_NAME, 
       UCC.COLUMN_NAME, 
       UC.CONSTRAINT_TYPE
FROM USER_CONSTRAINTS UC
JOIN USER_CONS_COLUMNS UCC ON (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
WHERE UC.TABLE_NAME = 'MEMBER';