/*
   <SEQUENCE>
      정수값을 자동으로 생성하는 역할을 하는 객채이다.      
*/


-- EMPLOYEE 테이블의 PK 값을 생성할 시퀀스 생성
CREATE SEQUENCE SEQ_EMPNO
START WITH 300
INCREMENT BY 5
MAXVALUE 310
NOCYCLE
NOCACHE;

-- 현재 계정이 가지고 있는 시퀀스들에 대한 정보를 조회하는 데이터 딕셔너리
SELECT * FROM USER_SEQUENCES;

-- NEXTVAL를 한번이라도 수행하지 않는 이상 CURRVAL를 가져올 수 없다.
SELECT SEQ_EMPNO.CURRVAL FROM DUAL;

SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 300
SELECT SEQ_EMPNO.CURRVAL FROM DUAL; -- 300
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 305
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 310
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- MAXVALUE 310 을 넘겼기 때문에 오류


/*
   <SEQUENCE 수정>
*/


-- ALTER로 수정
ALTER SEQUENCE SEQ_EMPNO
--START WITH 200; -- ERROR
INCREMENT BY 10
MAXVALUE 400;

-- 수정된 SEQUENCE 확인
SELECT * FROM USER_SEQUENCES;

SELECT SEQ_EMPNO.CURRVAL FROM DUAL; -- 310
SELECT SEQ_EMPNO.NEXTVAL FROM DUAL; -- 320


/*
   <SEQUENCE 삭제>
*/


-- DROP 이용
DROP SEQUENCE SEQ_EMPNO;

-- 삭제된 것 확인
SELECT * FROM USER_SEQUENCES;


--------------------------------------------------------------------------
-- 매번 새로운 사번이 발생되는 시퀀스 생성
CREATE SEQUENCE SEQ_EMPID
START WITH 300;

-- 확인해보기
SELECT * FROM USER_SEQUENCES;

-- EMP_ID가 저절로 증가되어 입력되어 있다.
INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO)
VALUES(SEQ_EMPID.NEXTVAL, '홍길동', '800930-1234567'); -- 300번으로 저장되어있음

INSERT INTO EMPLOYEE (EMP_ID, EMP_NAME, EMP_NO)
VALUES(SEQ_EMPID.NEXTVAL, '김삿갓', '910930-1234567'); -- 301번으로 저장되어있음

SELECT * FROM EMPLOYEE;

ROLLBACK;
