-- 4. 다중행 다중열 서브 쿼리
-- 비교 연산자 사용 불가

-- 1) 각 직급별로 최소 급여를 받는 사원들의 사번, 이름, 직급 코드, 급여를 조회
-- 내 방법
-- 각 직급별 최소 급여 조회
SELECT JOB_CODE, MIN(SALARY)
FROM EMPLOYEE
GROUP BY JOB_CODE;
가
-- 사원들의 사번, 이름, 직급 코드, 급여를 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE;

-- 조건을 넣어 합치기
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE
WHERE (JOB_CODE, SALARY) IN (
      SELECT JOB_CODE, MIN(SALARY)
      FROM EMPLOYEE
      GROUP BY JOB_CODE
)
ORDER BY JOB_CODE;


-- 선생님 방법
-- 각 직급별 최소 급여 조회
SELECT JOB_CODE, MIN(SALARY)
FROM EMPLOYEE
GROUP BY JOB_CODE;

-- 사원들의 사번, 이름, 직급 코드, 급여를 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE
WHERE JOB_CODE = 'J2' AND SALARY = 3700000 
      OR JOB_CODE = 'J7' AND SALARY = 1380000
      OR JOB_CODE = 'J3' AND SALARY = 3400000;

SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE
WHERE (JOB_CODE, SALARY) IN (('J2', 3700000), ('J7', 1380000), ('J3', 3400000));

-- 다중행 다중열 서브 쿼리를 사용해서 조회
SELECT EMP_ID, EMP_NAME, JOB_CODE, SALARY
FROM EMPLOYEE
WHERE (JOB_CODE, SALARY) IN (
      SELECT JOB_CODE, MIN(SALARY)
      FROM EMPLOYEE
      GROUP BY JOB_CODE
)
ORDER BY JOB_CODE;


-- 2) 각 부서별 최소 급여를 받는 사원들의 사원들의 사번, 이름, 부서 코드, 급여를 조회
-- 내 방법
SELECT NVL(DEPT_CODE,'부서없음'), MIN(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

SELECT EMP_ID, EMP_NAME, NVL(DEPT_CODE,'부서없음'), SALARY
FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, NVL(DEPT_CODE,'부서없음'), SALARY
FROM EMPLOYEE
WHERE (NVL(DEPT_CODE,'부서없음'), SALARY) IN (
      SELECT NVL(DEPT_CODE,'부서없음'), MIN(SALARY)
      FROM EMPLOYEE
      GROUP BY DEPT_CODE
)
ORDER BY DEPT_CODE;

-- 선생님 방법
-- 각 부서별 최소 급여 조회
SELECT NVL(DEPT_CODE,'부서없음'), MIN(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE;

-- 다중행 다중열 서브 쿼리를 사용해서 조회
SELECT EMP_ID, EMP_NAME, NVL(DEPT_CODE,'부서없음'), SALARY
FROM EMPLOYEE
WHERE (NVL(DEPT_CODE,'부서없음'), SALARY) IN (
      SELECT NVL(DEPT_CODE,'부서없음'), MIN(SALARY)
      FROM EMPLOYEE
      GROUP BY DEPT_CODE
)
ORDER BY DEPT_CODE;


