SELECT TO_CHAR('190505')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('190505','YYMMDD'),'YYYY"년" FMMM"월" DD"일"')
FROM DUAL;

SELECT EMP_NO, INITCAP(EMP_NAME)
FROM EMPLOYEE;

SELECT EMP_ID || ', ' || EMP_NAME || ', ' || DEPT_CODE
FROM EMPLOYEE;

SELECT CONCAT(EMP_ID,','), CONCAT(EMP_NAME,','),DEPT_CODE
FROM EMPLOYEE;

SELECT CONCAT(CONCAT(CONCAT(EMP_ID,', '),CONCAT(EMP_NAME,', ')),DEPT_CODE)
FROM EMPLOYEE;

-- 답으로 변환
SELECT CONCAT(CONCAT(CONCAT(EMP_ID,', '),CONCAT(EMP_NAME,', ')),EMP_DEPT)
FROM USER_TABLE;

SELECT DEPT_CODE, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING FLOOR(AVG(SALARY)) > 2800000
ORDER BY DEPT_CODE ASC;

-- 시험으로 변경
SELECT DEPT, SUM(SALARY) 합계, FLOOR(AVG(SALARY)) 평균, COUNT(*) 인원수
FROM EMP
GROUP BY DEPT
HAVING FLOOR(AVG(SALARY)) > 2800000
ORDER BY DEPT ASC;

--2 ROWNUM IN-LINE VIEW
SELECT ROWNUM, EMP_NAME, SALARY
FROM EMPlOYEE
WHERE ROWNUM <= 3
ORDER BY SALARY DESC;

-- EMPLOYEE 테이블로 
SELECT ROWNUM, EMP_NAME, SALARY
FROM EMPlOYEE
WHERE ROWNUM <= 5
ORDER BY SALARY DESC;

-- EMPLOYEE 테이블로 
SELECT ROWNUM, EMP_NAME, SALARY
FROM (
      SELECT *
      FROM EMPLOYEE
      ORDER BY SALARY DESC
)
WHERE ROWNUM <= 5;

-- 답으로 변환
SELECT ROWNUM, EMPNAME, SAL
FROM (
      SELECT *
      FROM EMP
      ORDER BY SAL DESC
)
WHERE ROWNUM <= 3;
