-- 5.

SELECT TO_DATE('210505','YYMMDD')
FROM DUAL;

SELECT TO_CHAR(TO_DATE('210505','YYMMDD'),'YYYY"년" MM"월" DD"일"')
FROM DUAL;

SELECT TO_DATE('210505','YY-MM-DD')
FROM DUAL;

SELECT SYSDATE
FROM DUAL;

-- 7.

SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME, SALARY
FROM EMPLOYEE, JOB, DEPARTMENT, LOCATION
WHERE EMPLOYEE.JOB_CODE = JOB.JOB_CODE
AND DEPT_CODE = DEPT_ID
AND LOCATION_ID = LOCAL_CODE
AND JOB_NAME = '대리'
AND LOCAL_NAME LIKE 'ASIA%';

SELECT *
FROM DEPARTMENT;

SELECT *
FROM JOB;

SELECT *
FROM EMPLOYEE;

SELECT EMPLOYEE.EMP_ID, EMPLOYEE.EMP_NAME, JOB.JOB_NAME, DEPARTMENT.DEPT_TITLE, LOCATION.LOCAL_NAME, EMPLOYEE.SALARY
FROM EMPLOYEE 
JOIN JOB ON (EMPLOYEE.JOB_CODE = JOB.JOB_CODE)
JOIN DEPARTMENT ON (EMPLOYEE.DEPT_CODE = DEPARTMENT.DEPT_ID)
JOIN LOCATION ON (DEPARTMENT.LOCATION_ID = LOCATION.LOCAL_CODE)
WHERE JOB_NAME = '대리' AND LOCAL_NAME LIKE 'ASIA%';

-- test
SELECT EMP_NAME, EMP_NO, DEPT_CODE, SALARY
FROM EMPLOYEE
WHERE (DEPT_CODE = 'D9' OR DEPT_CODE= 'D6') AND SALARY >= '3000000' 
       AND BONUS IS NOT NULL AND SUBSTR(EMP_NO,8,1) = 1 AND EMAIL LIKE '___$_%' ESCAPE '$';

SELECT * 
FROM EMPLOYEE 
WHERE BONUS IS NULL AND MANAGER_ID IS NOT NULL;


SELECT *
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,8,1) != 1;


SELECT *
FROM EMPLOYEE
WHERE EMAIL LIKE '___$_%' ESCAPE '$';


