INSERT INTO memberTb (id, pass, name, age)
VALUES ('0100', '1234', '이지은', 25);
INSERT INTO memberTb (id, pass, name, age)
VALUES ('0101', 'C33kimleechoi', '강한나', 30);
INSERT INTO memberTb (id, pass, name, age)
VALUES ('0102', 'snsd', '서주현', 28);

CREATE TABLE DEPARTMENT(
DEPTCODE NUMBER PRIMARY KEY, 
DEPTNAME NVARCHAR2(10) NOT NULL)
;

CREATE TABLE EMPLOYEE( 
EMPNO NUMBER PRIMARY KEY, 
EMPNAME VARCHAR2(10) NOT NULL, 
DEPTNO NUMBER REFERENCES DEPARTMENT(DEPTCODE)
);

SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPARTMENT.DEPTCODE = EMPLOYEE.DEPTNO);

SELECT EMPNO, EMPNAME, DEPTNO, DEPTNAME
FROM EMPLOYEE
JOIN DEPARTMENT USING(EMPLOYEE.DEPTNO);