----------------------------다중 JOIN 실습 문제-----------------------------
-- 1. 사번, 직원명, 부서명, 지역명, 국가명을 조회
-- ANSI
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, N.NATIONAL_NAME
FROM EMPLOYEE E  
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
JOIN NATIONAL N ON (L.NATIONAL_CODE = N.NATIONAL_CODE);

-- 오라클
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, N.NATIONAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L, NATIONAL N
WHERE (E.DEPT_CODE = D.DEPT_ID) AND (D.LOCATION_ID = L.LOCAL_CODE) 
      AND (L.NATIONAL_CODE = N.NATIONAL_CODE);
      

-- 2. 사번, 직원명, 부서명, 직급명, 지역명, 국가명, 급여 등급 조회
-- ANSI
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE, J.JOB_NAME, L.LOCAL_NAME, N.NATIONAL_NAME, S.SAL_LEVEL
FROM EMPLOYEE E
JOIN SAL_GRADE S ON (E.SALARY BETWEEN S.MIN_SAL AND S.MAX_SAL)
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
JOIN NATIONAL N ON (L.NATIONAL_CODE = N.NATIONAL_CODE);

-- 오라클
SELECT E.EMP_ID, E.EMP_NAME, D.DEPT_TITLE, J.JOB_NAME, L.LOCAL_NAME, N.NATIONAL_NAME, S.SAL_LEVEL
FROM EMPLOYEE E, SAL_GRADE S, DEPARTMENT D, JOB J, LOCATION L, NATIONAL N
WHERE (E.SALARY BETWEEN S.MIN_SAL AND S.MAX_SAL)AND(E.DEPT_CODE = D.DEPT_ID)AND
(E.JOB_CODE = J.JOB_CODE)AND(D.LOCATION_ID = L.LOCAL_CODE)AND(L.NATIONAL_CODE = N.NATIONAL_CODE);

-------------------------------------------------------------------------
-------------------------------종합 실습 문제-------------------------------


-- 1. 직급이 대리이면서 ASIA 지역에서 근무하는 직원들의 사번, 직원명, 직급명, 근무 지역, 급여를 조회
-- ANSI구문 E.EMP_ID, E.EMP_NAME, J.JOB_NAME, L.LOCAL_NAME, E.SALARY
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
WHERE J.JOB_NAME = '대리' AND L.LOCAL_NAME LIKE 'ASIA%';

-- 오라클 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME, L.LOCAL_NAME, E.SALARY
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L 
WHERE (E.JOB_CODE = J.JOB_CODE) AND(E.DEPT_CODE = D.DEPT_ID)AND 
     (D.LOCATION_ID = L.LOCAL_CODE)AND (J.JOB_NAME = '대리') AND (L.LOCAL_NAME LIKE 'ASIA%');


-- 2. 70년대생 이면서 여자이고, 성이 전 씨인 직원들의 직원명, 주민 등록 번호, 부서명을 조회
-- ANSI구문 
SELECT E.EMP_NAME , E.EMP_NO, D.DEPT_TITLE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
WHERE SUBSTR(E.EMP_NO,1,1) = 7 AND SUBSTR(E.EMP_NO,8,1) = 2 AND E.EMP_NAME LIKE '전%';

-- 오라클 구문
SELECT E.EMP_NAME , E.EMP_NO, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D
WHERE (E.DEPT_CODE = D.DEPT_ID) AND 
      SUBSTR(E.EMP_NO,1,1) = 7 AND SUBSTR(E.EMP_NO,8,1) = 2 AND E.EMP_NAME LIKE '전%';


-- 3. 보너스를 받는 직원들의 직원명, 보너스, 연봉, 부서명, 근무 지역을 조회
-- ANSI구문
SELECT E.EMP_NAME, E.BONUS, TO_CHAR(E.SALARY*12,'FML99,999,999')"연봉", D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
LEFT JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
WHERE BONUS IS NOT NULL ;

-- 오라클 구문
SELECT E.EMP_NAME, E.BONUS, TO_CHAR(E.SALARY*12,'FML99,999,999')"연봉", D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE (E.DEPT_CODE = D.DEPT_ID)AND (D.LOCATION_ID = L.LOCAL_CODE) AND BONUS IS NOT NULL ;


-- 4. 한국과 일본에서 근무하는 직원들의 직원명, 부서명, 근무 지역, 근무 국가를 조회
-- ANSI구문
SELECT E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, N.NATIONAL_NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
JOIN NATIONAL N ON (L.NATIONAL_CODE = N.NATIONAL_CODE)
WHERE N.NATIONAL_NAME IN ('한국','일본');

-- 오라클 구문
SELECT E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, N.NATIONAL_NAME
FROM EMPLOYEE E, DEPARTMENT D,LOCATION L, NATIONAL N
WHERE (E.DEPT_CODE = D.DEPT_ID)AND (D.LOCATION_ID = L.LOCAL_CODE) 
      AND (L.NATIONAL_CODE = N.NATIONAL_CODE) AND N.NATIONAL_NAME IN ('한국','일본');


-- 5. 각 부서별 평균 급여를 조회하여 부서명, 평균 급여를 조회 (단, 부서 배치가 안된 사원들의 평균도 출력)
-- ANSI구문 
SELECT NVL(D.DEPT_TITLE,'부서 없음')"부서명", TO_CHAR(ROUND(AVG(NVL(E.SALARY,0))),'FML99,999,999') "평균 급여"
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
GROUP BY D.DEPT_TITLE;

-- 오라클 구문
SELECT NVL(D.DEPT_TITLE,'부서 없음')"부서명", TO_CHAR(ROUND(AVG(NVL(E.SALARY,0))),'FML99,999,999') "평균 급여"
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPT_CODE = D.DEPT_ID (+)
GROUP BY D.DEPT_TITLE;


-- 6. 각 부서별 총 급여의 합이 1000만원 이상인 부서명, 급여의 합을 조회
-- ANSI구문
SELECT D.DEPT_TITLE, TO_CHAR(SUM(E.SALARY),'FML99,999,999') "급여의 합"
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
GROUP BY D.DEPT_TITLE
HAVING SUM(E.SALARY) >= 10000000;

-- 오라클 구문
SELECT D.DEPT_TITLE, TO_CHAR(SUM(E.SALARY),'FML99,999,999') "급여의 합"
FROM EMPLOYEE E, DEPARTMENT D 
WHERE (E.DEPT_CODE = D.DEPT_ID)
GROUP BY D.DEPT_TITLE
HAVING SUM(E.SALARY) >= 10000000;


-- 7. 사번, 직원명, 직급명, 급여 등급, 구분을 조회
-- 이때 구분에 해당하는 값은 아래와 같이 조회되도록 하시오.
-- 급여 등급이 S1, S2인 경우 '고급'
-- 급여 등급이 S3, S4인 경우 '중급'
-- 급여 등급이 S5, S6인 경우 '초급'
-- ANSI구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME,
       CASE WHEN S.SAL_LEVEL IN ('S1', 'S2') THEN '고급'
            WHEN S.SAL_LEVEL IN ('S3', 'S4') THEN '중급'
            WHEN S.SAL_LEVEL IN ('S5', 'S6') THEN '초급'
       END AS "급여 등급"
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
JOIN SAL_GRADE S ON (E.SALARY BETWEEN S.MIN_SAL AND S.MAX_SAL);

-- 오라클 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME,
       CASE WHEN S.SAL_LEVEL IN ('S1', 'S2') THEN '고급'
            WHEN S.SAL_LEVEL IN ('S3', 'S4') THEN '중급'
            WHEN S.SAL_LEVEL IN ('S5', 'S6') THEN '초급'
       END AS "급여 등급"
FROM EMPLOYEE E, JOB J, SAL_GRADE S
WHERE (E.JOB_CODE = J.JOB_CODE) AND (E.SALARY BETWEEN S.MIN_SAL AND S.MAX_SAL);


-- 8. 보너스를 받지 않는 직원들 중 직급 코드가 J4 또는 J7인 직원들의 직원명, 직급명, 급여를 조회
-- ANSI구문 E.EMP_NAME, J.JOB_NAME, E.SALARY
SELECT E.EMP_NAME, J.JOB_NAME, TO_CHAR(E.SALARY,'FML99,999,999')"급여"
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE BONUS IS NULL AND (E.JOB_CODE ='J4' OR  E.JOB_CODE = 'J7');

-- 오라클 구문
SELECT E.EMP_NAME, J.JOB_NAME, TO_CHAR(E.SALARY,'FML99,999,999')"급여"
FROM EMPLOYEE E, JOB J 
WHERE (E.JOB_CODE = J.JOB_CODE) AND (E.JOB_CODE ='J4' OR E.JOB_CODE = 'J7') AND BONUS IS NULL;


-- 9. 해외영업팀에 근무하는 직원들의 직원명, 직급명, 부서 코드, 부서명을 조회
-- ANSI구문
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_ID, D.DEPT_TITLE
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (E.DEPT_CODE = D.DEPT_ID)
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
JOIN LOCATION L ON (D.LOCATION_ID = L.LOCAL_CODE)
WHERE L.NATIONAL_CODE != 'KO'  AND D.DEPT_TITLE LIKE '%영업%';

-- 오라클 구문
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_ID, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D, JOB J, LOCATION L
WHERE (E.DEPT_CODE = D.DEPT_ID) AND (E.JOB_CODE = J.JOB_CODE) AND (D.LOCATION_ID = L.LOCAL_CODE) 
AND L.NATIONAL_CODE != 'KO'  AND D.DEPT_TITLE LIKE '%영업%';


-- 10. 이름에 '형'자가 들어가는 직원들의 사번, 직원명, 직급명을 조회
-- ANSI구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E
JOIN JOB J ON (E.JOB_CODE = J.JOB_CODE)
WHERE E.EMP_NAME LIKE '%형%';

-- 오라클 구문
SELECT E.EMP_ID, E.EMP_NAME, J.JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE (E.JOB_CODE = J.JOB_CODE) AND E.EMP_NAME LIKE '%형%';
-------------------------------------------------------------------------